---
title:
  - type: main
    text: The Tale of Plack
creator:
  - role: author
    text: Tatsuhiko Miyagawa (宮川達彦）
  - role: editor
    text: Daisuke Maki （牧大輔）
identifier: http://yapcasia.org/2010/talks/63D5EA98-BC8C-11DF-8791-B9FC0F276C45
language: ja-JP
rights: (c) 2014 Japan Perl Association, CC BY-NC
x-yapcasia:
  amazon_link: http://www.amazon.co.jp/gp/product/B00NK6NW7Y/ref=as_li_qf_sp_asin_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B00NK6NW7Y&linkCode=as2&tag=jpaperl-22
