---
title:
  - type: main
    text: 本当にあったレガシーな話
creator:
  - role: author
    text: Daisuke Maki (牧大輔）
language: ja-JP
rights: (c) 2014 Japan Perl Association, CC BY-NC
x-yapcasia:
  amazon_link: TBD
