---
title:
  - type: main
    text: PSGI/Plack・Monocerosで学ぶハイパフォーマンスWebアプリケーションサーバの作り方
creator:
  - role: author
    text: Masahiro Nagano （長野雅広）
  - role: editor
    text: Haruna Kudo （工藤春奈）
identifier: http://yapcasia.org/2013/talk/show/1ae09aba-c8d5-11e2-a1f8-59856aeab6a4
language: ja-JP
rights: (c) 2014 Japan Perl Association, CC BY-NC
x-yapcasia:
  amazon_link: TBD

