---
title:
  - type: main
    text: MojoliciousでつくるWebアプリ入門
creator:
  - role: author
    text: Yusuke Wada (和田裕介）
language: ja-JP
rights: (c) 2014 Japan Perl Association, CC BY-NC
x-yapcasia
  amazon_link: TBD